name: drqv2
channels:
  - defaults
dependencies:
  - python=3.8
  - pip=21.1.3
  - numpy
  - absl-py=0.13.0
  - pyparsing=2.4.7
  - jupyterlab=3.0.14
  - scikit-image=0.18.1
  - nvidia::cudatoolkit=10.2
  - pytorch::pytorch=1.9.0
  - pytorch::torchvision=0.10.0
  - pytorch::torchaudio=0.9.0
  - pip:
    - termcolor==1.1.0
    - git+git://github.com/deepmind/dm_control.git@892b4e4e298825e86cd0364619bf4e36258f71d2
    - tb-nightly
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.4
    - hydra-core==1.1.0
    - hydra-submitit-launcher==1.1.5
    - pandas==1.3.0
    - ipdb==0.13.9
    - yapf==0.31.0
    - mujoco_py==2.0.2.13
    - sklearn==0.0
    - matplotlib==3.4.2
    - opencv-python==4.5.3.56
    - git+git://github.com/rlworkgroup/metaworld.git@master#egg=metaworld
